---

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    container_name: db-mysql
    hostname: db-mysql
    ports:
      - "3306:3306"
      - "33060:33060"
  # sqlite:
  #   image: alpine/sqlite:latest
  #   restart: always
  #   container_name: db-sqlite
  #   hostname: db-sqlite
    