---
name: test-mysql
on:
  workflow_dispatch:

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: start mysql
        run: |
          docker compose up -d
          sleep 60
          docker ps -a
      - name: create blank schema
        env:
          MYS_USR: ${{ secrets.MYS_USR }}
          MYS_PWD: ${{ secrets.MYS_PWD }}
        run: |
          echo "create blank schema"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -e "create schema sakila;"
          echo "create table and populate data"
          docker exec -i db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -D sakila < test2/migrations/B0_1__Create_tables.sql
          echo "count film table"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -D sakila -e "select count(*) from film;"
          echo "list tables in schema"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -e "select * from information_schema.TABLES where TABLE_SCHEMA = 'sakila'; and TABLE_NAME like 'TABLE%'"

      - name: first flyway deploy
        run: |
          docker run --rm --name fw-cli --network fw-mysql_default \
          -v ${CWD}:/flyway/project \
          flyway/flyway \
          -workingDirectory="project" \
          -locations="filesystem:migrations_v2" \
          migrate

      - name: verify migration
        run: |
          echo "list tables in schema"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -e "select * from information_schema.TABLES where TABLE_SCHEMA = 'sakila'; and TABLE_NAME like 'TABLE%'"

      - name: stop mysql
        env:
          MYS_USR: ${{ secrets.MYS_USR }}
          MYS_PWD: ${{ secrets.MYS_PWD }}
        run: |
          docker compose down
