---
name: test-mysql
on:
  workflow_dispatch:

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: start mysql
        run: |
          docker compose up -d
          sleep 60
          docker ps -a
      - name: create blank schema
        env:
          MYS_USR: ${{ secrets.MYS_USR }}
          MYS_PWD: ${{ secrets.MYS_PWD }}
        run: |
          echo "create blank schema"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -e "create schema sakila;"
          echo "create table and populate data"
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} < test2/migrations/B0_1__Create_tables.sql
      - name: stop mysql
        run: |
          docker exec db-mysql mysql -u${MYS_USR} -p${MYS_PWD} -e "select count(*) from film;"
          docker compose down
